package portal

// Code generated by go generate; DO NOT EDIT.

var CSPHashes = [][2]string{
	{"script", "'sha256-ZL1RLVKqPe4IS+tWzALaHASjuTMNpKU+PxE2hSXltwI='"},
	{"style", "'sha256-jYkyVpDPhRMIJvL/SfmKfI29+jn164evEl/99e3c860='"},
}
