package portal

// Code generated by go generate; DO NOT EDIT.

var CSPHashes = [][2]string{
	{"script", "'sha256-JaTfunWdzXQCIV4vo3/B7WTNrf9FWixwP54ryYr0M64='"},
	{"style", "'sha256-NGh8KkP6xLorPzXB/lrGeJraiEskRbDHyMlkkJ41GHg='"},
}
