package portal

// Code generated by go generate; DO NOT EDIT.

var CSPHashes = [][2]string{
	{"script", "'sha256-hLONftYIVHh7fBj54sE30p8qve0O00r4B9m49dG/R78='"},
	{"style", "'sha256-znjmTepgvpYiRmkyQzL7nWSUF5gedE/aPakoPyXJSBs='"},
}
