//go:build ignore

package main

import (
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"os"
	"regexp"
	"strings"
)

func main() {
	html, err := os.ReadFile("dashboard.html")
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read dashboard.html: %v\n", err)
		os.Exit(1)
	}

	content := string(html)

	scriptRe := regexp.MustCompile(`(?s)<script>(.+?)</script>`)
	styleRe := regexp.MustCompile(`(?s)<style>(.+?)</style>`)

	scripts := scriptRe.FindAllStringSubmatch(content, -1)
	styles := styleRe.FindAllStringSubmatch(content, -1)

	var out strings.Builder
	out.WriteString("package portal\n\n")
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	out.WriteString("var CSPHashes = [][2]string{\n")
	for _, m := range scripts {
		h := sha256.Sum256([]byte(m[1]))
		out.WriteString(fmt.Sprintf("\t{\"script\", \"'sha256-%s'\"},\n", base64.StdEncoding.EncodeToString(h[:])))
	}
	for _, m := range styles {
		h := sha256.Sum256([]byte(m[1]))
		out.WriteString(fmt.Sprintf("\t{\"style\", \"'sha256-%s'\"},\n", base64.StdEncoding.EncodeToString(h[:])))
	}
	out.WriteString("}\n")

	err = os.WriteFile("csp_gen.go", []byte(out.String()), 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to write csp_gen.go: %v\n", err)
		os.Exit(1)
	}
}